### ISSUE TITLE
Error traceback 

### ISSUE THREAD

**Issue by Azef1** [descrepes/mod-elastic-logs#2]
Hi,
I try to use your module but i have some errors in my brokerd.log:

> [1458223473] ERROR: [broker] [elastic-logs] Traceback (most recent call last):
>   File "/var/lib/shinken/modules/elastic-logs/module.py", line 465, in main
>   File "/var/lib/shinken/modules/elastic-logs/module.py", line 197, in manage_brok
>   File "/var/lib/shinken/modules/elastic-logs/module.py", line 266, in manage_service_check_result_brok
> [1458223474] ERROR: [broker] The external module elastic-logs goes down unexpectedly!
> [1458223474] INFO: [broker] Setting the module elastic-logs to restart
> [1458223474] INFO: [broker] Trying to init module: elastic-logs
> [1458223475] INFO: [broker] Trying to init module: elastic-logs
> [1458223475] INFO: [broker] I'm stopping module u'elastic-logs' (pid=21535)
> [1458223475] INFO: [broker] Starting external process for instance elastic-logs

Have an idea to fix it ?
Thx to have developed this module.

I using shinken 2.4 and i edited in this file:  /etc/shinken/modules/elastic-logs.cfg to add:

> services_filter bi:>0
> It's to have all services

This module send availability logs or not ?

**Comment by descrepes** [comment]
Hi,

There is a bug.
The version 1.0.1 should fix the issue.
The module does not send any availability logs for the moment but any help is welcome on this :)

You can update your module via shinken.io or downloading the 1.0.1 release.
Let me know if the new version fix your issue.

Regards.

**Comment by Azef1** [comment]
Yes it work now. Thx you very much.

About availability logs:
In my project i must send availability logs to Elasticsearch. Currently, I am editing the mod-mongo-logs to send availability logs to mongoDB and ElasticSearch.
In line 567, the function replace_one insert/update log in mongoDB. Me i am adding a similar function for ElasticSearch with the ElasticSearch python module.
`https://github.com/shinken-monitoring/mod-mongo-logs/blob/master/module/module.py#L567`
But it's not a clean solution. If your module could send availability logs It would be amazing.
