### ISSUE TITLE
Whitespace on service_description field

### ISSUE THREAD

**Issue by Azef1** [descrepes/mod-elastic-logs#3]
Hi,

Your module works well, but in kibana i have a problem on fileld "service_description":
When the field contains whitespace Kibana separate terms.
Eg: service_description: "NGINX: WebServer" Kibana cut the string in two words (NGINX: and WebServer).
So, it's difficult to do some graphs on this field.

From this website: [here](https://github.com/elastic/kibana/issues/792) the solution is to set string field mapping as not_analyzed.

**Comment by descrepes** [comment]
Hi,

That's a matter of ES mapping.
The module does not managed the mapping.
If you want to to modify it, you have to do it on ES.

You can use the following mapping:
`
{
    "template" : "shinken-*",
    "settings" : {
      "index" : {
        "refresh_interval" : "5s"
      }
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [ {
          "message_field" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "fielddata" : {
                "format" : "disabled"
              },
              "type" : "string"
            },
            "match_mapping_type" : "string",
            "match" : "message"
          }
        }, {
          "string_fields" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "fielddata" : {
                "format" : "disabled"
              },
              "type" : "string",
              "fields" : {
                "raw" : {
                  "index" : "not_analyzed",
                  "ignore_above" : 256,
                  "doc_values" : true,
                  "type" : "string"
                }
              }
            },
            "match_mapping_type" : "string",
            "match" : "*"
          }
        }, {
          "float_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "float"
            },
            "match_mapping_type" : "float",
            "match" : "*"
          }
        }, {
          "double_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "double"
            },
            "match_mapping_type" : "double",
            "match" : "*"
          }
        }, {
          "byte_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "byte"
            },
            "match_mapping_type" : "byte",
            "match" : "*"
          }
        }, {
          "short_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "short"
            },
            "match_mapping_type" : "short",
            "match" : "*"
          }
        }, {
          "integer_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "integer"
            },
            "match_mapping_type" : "integer",
            "match" : "*"
          }
        }, {
          "long_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "long"
            },
            "match_mapping_type" : "long",
            "match" : "*"
          }
        }, {
          "date_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "date"
            },
            "match_mapping_type" : "date",
            "match" : "*"
          }
        }, {
          "geo_point_fields" : {
            "mapping" : {
              "doc_values" : true,
              "type" : "geo_point"
            },
            "match_mapping_type" : "geo_point",
            "match" : "*"
          }
        } ],
        "properties" : {
          "@timestamp" : {
            "doc_values" : true,
            "type" : "date"
          },
          "geoip" : {
            "dynamic" : true,
            "properties" : {
              "location" : {
                "doc_values" : true,
                "type" : "geo_point"
              },
              "longitude" : {
                "doc_values" : true,
                "type" : "float"
              },
              "latitude" : {
                "doc_values" : true,
                "type" : "float"
              },
              "ip" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fields" : {
                  "raw" : {
                    "type" : "string",
                    "index" : "not_analyzed",
                    "ignore_above" : 256
                  }
                }
              }
            },
            "type" : "object"
          },
          "@version" : {
            "index" : "not_analyzed",
            "doc_values" : true,
            "type" : "string"
          }
        },
        "_all" : {
          "enabled" : true,
          "omit_norms" : true
        }
      }
    },
    "aliases" : { }
}
`

Regards
